- voicer-client/package.json
- voicer-client/src/__tests__/sample.js
- voicer-client/yarn.lock
Enables front end testing with jest.
> Front end testing

- voicer-client/src/components/ClientNavigation.js
Added a simple client navigation.
> Client navigation

- netlify.toml
Configured netlify.toml file to build correctly and get react router working
> netlify added

- voicer-client/.gitignore
- voicer-client/package.json
- voicer-client/src/App.js
- voicer-client/src/actions/getClientProfile.js
- voicer-client/src/actions/index.js
- voicer-client/src/actions/login.js
- voicer-client/src/actions/register.js
- voicer-client/src/components/ClientProfile.js
- voicer-client/src/components/Login/Login.js
- voicer-client/src/components/Login/PrivateRoute.js
- voicer-client/src/components/Register.js
- voicer-client/src/index.js
- voicer-client/src/reducers/clientProfileReducer.js
- voicer-client/src/reducers/loginReducer.js
- voicer-client/yarn.lock
Client and talent profile creation upon registering completed, cleaned up some localStorage code, and implemented login routing
> Client talent creation/Login routing

- voicer-client/src/actions/getClientProfile.js
- voicer-client/src/actions/getJobs.js
- voicer-client/src/actions/login.js
- voicer-client/src/actions/postJob.js
- voicer-client/src/actions/register.js
> Added axiosWithAuth to the front end

- voicer-client/src/actions/filterData.js
- voicer-client/src/components/FilterComponents/FilterComponent.js
- voicer-client/src/components/FilterComponents/PaymentFilter.js
- voicer-client/src/components/FilterComponents/SearchFilter.js
- voicer-client/src/components/FilterComponents/SortFilter.js
- voicer-client/src/components/FilterComponents/StarFilter.js
- voicer-client/src/components/TalentHomePage.js
- voicer-client/src/reducers/filterReducer.js
…talentHomePage
Cleaned up filter components and reducers to be more reusable and streamlined
I removed unused functions, and added some comments
changed state holding filter data around
you can specify keys to target in the data
> Changed filter state around and cleaned up all of the components as well

- voicer-client/src/App.js
- voicer-client/src/actions/getApplications.js
- voicer-client/src/actions/getJobs.js
- voicer-client/src/actions/index.js
- voicer-client/src/actions/postJob.js
- voicer-client/src/actions/setJobId.js
- voicer-client/src/components/Applications/AppList.js
- voicer-client/src/components/ClientHomePage.js
- voicer-client/src/components/ClientNavigation.js
- voicer-client/src/components/FilterComponents/FilterComponent.js
- voicer-client/src/components/FilterComponents/SearchFilter.js
- voicer-client/src/components/JobInfo.js
- voicer-client/src/components/JobList/ClientJobList.js
- voicer-client/src/components/JobList/ClientJobListCard.js
- voicer-client/src/components/JobList/JobListCard.js
- voicer-client/src/components/PostJob.js
- voicer-client/src/components/TalentHomePage.js
- voicer-client/src/components/TalentList/TalentList.js
- voicer-client/src/components/TalentList/TalentListCard.js
- voicer-client/src/components/TalentNavigation.js
- voicer-client/src/reducers/getJobOffersReducer.js
- voicer-client/src/reducers/getTalentReducer.js
- voicer-client/src/styles/styledComponents/ClientListCard.js
- voicer-client/src/styles/styledComponents/Container.js
- voicer-client/src/styles/styledComponents/JobListCard.js
Made setJobId to pass jobId to TalentList and ApplicationList.
Styled ClientJobListCard.
Fixed TalentList.
> Talent list

- voicer-client/src/App.js
- voicer-client/src/actions/getApplications.js
- voicer-client/src/actions/getJobs.js
- voicer-client/src/actions/index.js
- voicer-client/src/actions/postJob.js
- voicer-client/src/actions/setJobId.js
- voicer-client/src/components/Applications/AppList.js
- voicer-client/src/components/ClientHomePage.js
- voicer-client/src/components/ClientNavigation.js
- voicer-client/src/components/FilterComponents/FilterComponent.js
- voicer-client/src/components/FilterComponents/SearchFilter.js
- voicer-client/src/components/JobInfo.js
- voicer-client/src/components/JobList/ClientJobList.js
- voicer-client/src/components/JobList/ClientJobListCard.js
- voicer-client/src/components/JobList/JobListCard.js
- voicer-client/src/components/PostJob.js
- voicer-client/src/components/TalentHomePage.js
- voicer-client/src/components/TalentNavigation.js
- voicer-client/src/reducers/getJobOffersReducer.js
- voicer-client/src/reducers/getTalentReducer.js
- voicer-client/src/styles/styledComponents/ClientListCard.js
- voicer-client/src/styles/styledComponents/Container.js
- voicer-client/src/styles/styledComponents/JobListCard.js
Styling Client Home Page.
Passing JobId to Redux store in button onClicks.
> Waiting on BackEnd: Styling client home page

- voicer-client/src/components/ApplyToJob.js
- voicer-client/src/components/TalentList/TalentList.js
ApplyToJob clickHandler needed to be updated to match the change in the jobOffer table.
> Fixing apply

- node_modules/.yarn-integrity
- voicer-client/package.json
- voicer-client/src/components/TalentProfile.js
- voicer-client/src/styles/talent-profile.css
- voicer-client/yarn.lock
> Finished styling for the Talent Component.

- voicer-client/src/components/Talent/TalentOfferView.js
Refresh job list on componentDidMount
Fixes issue of jobs being cleared on refresh
> fixed a function to refresh jobs when refreshing the page

- voicer-client/src/actions/talentBio.js
- voicer-client/src/components/Talent/TalentProfile.js
> Fixed bug to save all values the the talent profile on the backend.

- voicer-client/src/components/Talent/TalentProfile.js
Added loyaltyLevel badge to talentProfile.
> added loyaltyLevel badge to Talent Profile

- voicer-client/src/actions/addSample.js
- voicer-client/src/actions/index.js
- voicer-client/src/components/Talent/TalentProfileSample.js
Adding S3 object URL for uploaded file to database
> AWS uploads: Add S3 URL to database

- voicer-client/src/actions/getTalents.js
- voicer-client/src/components/ClientHomePage.js
- voicer-client/src/components/ClientProfile.scss
- voicer-client/src/components/JobList/ClientJobList.js
- voicer-client/src/components/PostJob.js
- voicer-client/src/components/TalentList/TalentListCard.js
- voicer-client/src/reducers/getTalentsReducer.js
> Misc. GUI/Styling fixes

- voicer-client/src/components/Talent/TalentProfileSample.js
- voicer-client/src/styles/talent-samples.scss
> Added description field

- voicer-client/src/actions/getClient.js
- voicer-client/src/actions/getTalents.js
- voicer-client/src/actions/index.js
- voicer-client/src/actions/submitReview.js
- voicer-client/src/components/Applications/AppCard.js
- voicer-client/src/components/JobList/ClientJobList.js
- voicer-client/src/components/PostJob.js
- voicer-client/src/components/ReviewModal.js
- voicer-client/src/components/Talent/TalentOffersCard.js
- voicer-client/src/reducers/getClientReducer.js
- voicer-client/src/reducers/submitReviewReducer.js
connects the review modal to the completed job list. This is to leave a review of the talent.
2
Connect reviewModal to AppCard and pass relevant data
Fixed two old dbUrls
> Connected the review modal to the completed job list

- voicer-client/src/App.js
- voicer-client/src/components/ClientNavigation.js
Adds review tab to client navigation.
> Add reviews tab to client navigation

- voicer-client/src/App.js
- voicer-client/src/App.scss
- voicer-client/src/components/marketplace/JobsCard.jsx
- voicer-client/src/components/marketplace/Marketplace.jsx
- voicer-client/src/components/voice/Voice.jsx
Fixed styling on marketplace component. Should have happened on `marketplace-component`, but is what it is.
> fixed marketplace styling

- voicer-client/src/App.scss
- voicer-client/src/components/audio/AudioPlayer.jsx
- voicer-client/src/components/navbar/login/logRegFields.js
- voicer-client/src/components/voice/Attributes.jsx
- voicer-client/src/components/voice/Samples.jsx
- voicer-client/src/components/voice/VoiceItem.jsx
> added sample view

- voicer-client/package.json
- voicer-client/src/components/editor/Editor.jsx
- voicer-client/src/components/navbar/NavBar.jsx
- voicer-client/src/components/voice/EditProfile.jsx
- voicer-client/yarn.lock
> added an editor, it doesn't work correctly yet

- voicer-client/src/components/editor/Editor.jsx
- voicer-client/src/components/voice/EditProfile.jsx
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] Complete, but not tested (may need new tests)
This feature has not yet been tested
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] My code has been reviewed by at least one peer
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ x] There are no merge conflicts
> added functionality to edit profiles

- voicer-client/src/components/axiosWithAuth/axiosWithAuth.js
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] Complete, but not tested (may need new tests)
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] My code has been reviewed by at least one peer
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] New and existing unit tests pass locally with my changes
- [x ] There are no merge conflicts
> added an axios authorization component

- voicer-client/src/App.scss
- voicer-client/src/components/audio/AudioPlayer.jsx
- voicer-client/src/components/voice/VoiceItem.jsx
> Audioplayback

- voicer-client/package-lock.json
- voicer-client/package.json
- voicer-client/src/components/audio/AudioPlayer.jsx
- voicer-client/src/components/audio/AudioRecorder.jsx
- voicer-client/src/components/axiosWithAuth/axiosWithAuth.js
- voicer-client/src/components/voice/EditProfile.jsx
> Add AudioRecorder

- voicer-client/package.json
- voicer-client/src/App.scss
- voicer-client/src/components/addJobForm/AddJobForm.jsx
- voicer-client/src/components/marketplace/Marketplace.jsx
- voicer-client/src/components/navbar/NavBar.jsx
- voicer-client/src/index.js
- voicer-client/yarn.lock
- Added a form to add a job and pre-pended it to Marketplace for the
sake of easy use
- Later, will refactor to be hidden and appear when someone clicks a link
to add a job
- Separately, imported bootstrap and node-sass for eventual
react-bootstrap styling (currently works but have commented out due to
styling conflict)
> Added a AddJobComponent & imported bootstrap

- voicer-client/src/components/navbar/AllUsers.jsx
- voicer-client/src/components/navbar/Logo.jsx
- voicer-client/src/components/navbar/Logout.jsx
- voicer-client/src/components/navbar/Marketplace.jsx
- voicer-client/src/components/navbar/MyProfile.jsx
- voicer-client/src/components/navbar/NavBar.jsx
- voicer-client/src/components/navbar/PostAJob.jsx
Navbar had too many lines according to codeclimate, refactored into smaller components, will likely cause merge conflicts, so once we get the other two pulls accepted and merged, we'll need to fix it again
complexity
> Navbar refactor

- voicer-client/src/components/audio/AudioRecorder.jsx
> Add uploader form

- voicer-client/src/components/audio/AudioUploader.jsx
- voicer-client/src/components/voice/EditProfile.jsx
- voicer-client/src/components/voice/VoiceItem.jsx
> Fix uploader object bug, relocate to voiceItem, and pass context

- README.md
> fixed j0liver, was wrong profile and photo

- voicer-client/src/components/marketplace/Marketplace.jsx
- voicer-client/src/components/voice/VoiceItem.jsx
> Moved AddJobForm to Voice component from Marketplace

- voicer-client/package.json
- voicer-client/src/components/audio/AudioPlayer.jsx
- voicer-client/src/components/voice/Voice.jsx
- voicer-client/yarn.lock
we discussed a way to search tags (or attributes), this is one implementation of a "live search style"
feature request
> added search functionality to voice path

- .github/workflows/node.js.yml
jest+github actions+ code climate setup
adding in more code climate testing with github actions
> Created node.js.yml file

- .github/workflows/node.js.yml
cd does not work, so tried working directory
> added cd voicer-client to action run list

- .github/workflows/node.js.yml
> trying again

- voicer-client/src/components/audio/AudioPlayer.jsx
- voicer-client/src/components/audio/AudioUploader.jsx
- voicer-client/src/components/audio/Samples.jsx
- voicer-client/src/components/voice/VoiceItem.jsx
Moved attributeForm from voice to audioplayer.
Adding conditional render logic for audioplayer to add an attribute if
logged in.
Building out render in audioplayer component.
Still to be done: Add crud to attributes
> Adding CRUD to sample attributes

- voicer-client/package.json
- voicer-client/src/components/voice/AttributeForm.jsx
- voicer-client/src/components/voice/Voice.jsx
- voicer-client/src/components/voice/VoiceItem.jsx
- voicer-client/yarn.lock
ci is failing due to bugs in system, also we had no testing before, added changes to allow test to run
> added testing

- voicer-client/src/components/audio/AudioPlayer.jsx
- voicer-client/src/components/voice/AttributeForm.jsx
- voicer-client/src/components/voice/VoiceItem.jsx
> Added ability to upload new Attributes to a sample

- .github/workflows/node.js.yml
- .gitignore
- voicer-client/package.json
> added coverage to test

- voicer-client/src/components/marketplace/JobsCard.jsx
Render job description instead of Lorum Ipsum
> Fixed job description display

- voicer-client/src/components/voice/AttributeForm.jsx
- Made it so users can delete or add tags dynamically without refreshing
the app.
> Improved tags functionality on AudioSample

- voicer-client/src/components/audio/AttributeForm.jsx
- voicer-client/src/components/audio/AudioPlayer.jsx
- voicer-client/src/components/audio/Tag.jsx
- [x ] Bug fix (non-breaking change which fixes an issue)
> Bug fix/attribute not rerendering

- voicer-client/src/components/audio/AttributeForm.jsx
- voicer-client/src/components/audio/Tag.jsx
Attributes are associated with AudioSamples so it makes more sense
to have it there. Also deleted a few unnecessary lines / comments.
Finally, moved Tag into its own component.
> Moved AttributeForm to the AudioSample Folder

- voicer-client/package.json
- voicer-client/src/components/audio/AttributeForm.jsx
- voicer-client/src/components/audio/Tag.jsx
- voicer-client/src/components/audio/Tag.test.js
- voicer-client/src/components/voice/Voice.jsx
> Added unit testing to Tag.jsx

- voicer-client/src/components/audio/AudioUploader.jsx
- voicer-client/src/components/voice/ProfileTabPanel.jsx
- voicer-client/src/components/voice/Voice.jsx
- voicer-client/src/components/voice/VoiceCard.jsx
> Remove code causing warnings

- voicer-client/src/App.scss
- voicer-client/src/components/audio/AttributeForm.jsx
- voicer-client/src/components/voice/ProfileTabPanel.jsx
- voicer-client/src/components/voice/VoiceItem.jsx
- voicer-client/src/components/voice/VoiceStyle.js
> crud and style submit button

- voicer-client/.github/workflows/ci.yml
possible fix for coverage locations
> Add yml coverage locations
